package com.squer.promobee.api.v1.enums

enum class SLVTypeEnum(val type: String) {
    USER_STATUS("USER_STATUS"),
    UPLOAD_TYPE("UPLOAD_TYPE"),
    UPLOAD_STATUS("UPLOAD_STATUS"),
    SCHEDULER_STATUS("SCHEDULER_STATUS"),
    SCHEDULER_JOB("SCHEDULER_JOB"),
    QUARTER_PLAN("QUARTER_PLAN"),
    INVOICE_STATUS("INVOICE_STATUS"),
    ALLOCATION("ALLOCATION"),
    APPROVAL_STATUS("APPROVAL_STATUS"),
    TICKET_STATUS("TICKET_STATUS"),
    PO_STATUS("PO_STATUS"),
    DISPLAY_PO_STATUS("DISPLAY_ITEM_REQUISITION"),
    REVALIDATION_STATUS("REVALIDATION_STATUS"),
    MONTHLY_PLAN_STATUS("MONTHLY_PLAN_STATUS"),
    DISPATCH_PLAN_INVOICE_STATUS("DISPATCH_PLAN_INVOICE_STATUS")
}